
//<debug>
Ext.Loader.setPath({
    'Ext': 'lib/touch/src',
    'Preventa': 'app'
});
//</debug>


Ext.application({
    name: 'Preventa',
    
    models: ['ComercialModel', 'SessionsModel', 'ProductModel', 'CategoryModel', 'UnitatsModel', 'ProductsUnitsModel', 'ClientModel', 'ProductsClientsModel', 'CommandModel', 'CommandProductModel'],
    stores: ['ComercialStore', 'SessionsStore', 'ProductsStore', 'CategoriesStore', 'UnitatsStore', 'ProductsUnitsStore', 'ClientsStore', 'ProductsClientsStore', 'CommandsStore', 'CommandProductStore'],
    controllers: ['SessionsController', 'CatalegController', 'EscollirClientController', 'CatalegClientController', 'InfoClientController'],
    views: ['LoginComercial', 'CatalegCategories',  'CatalegClientPortrait', 'CatalegCategoriesPortrait', 'CatalegProductes', 'CatalegProductesPortrait', 'DetailProduct', 'EscollirClient', 'CatalegClient', 'InfoClient', 'DetailCommand', 'DetailProductPortrait'],

    launch: function() {
    	console.log("Preventa: Application launched.");
    	
    	console.log("Size of the window: " + window.innerWidth + " x " + window.innerHeight);
    	
		var sessions = Ext.getStore('SessionsStore');
		console.log("Load store 'sessions' with : " + sessions.getCount() + " values.");
		
		var commandsProducts = this.loadCommandsProducts();
		console.log("Load store 'commandProduct' with : " + commandsProducts.getCount() + " values.");
		
		var commands = this.loadCommands();
		console.log("Load store 'commands' with : " + commands.getCount() + " values.");
    
        var loginComercial = { xtype: 'LoginComercial' };
        var catalegCategories = {xtype: 'CatalegCategories'};
        var catalegProducts = {xtype: 'CatalegProductes'};
        var detailProduct = {xtype: 'DetailProduct'};
        var escollirClient = {xtype: 'EscollirClient'};
        var catalegClient = {xtype: 'CatalegClient'};
        var infoClient = {xtype: 'InfoClient'};
        var detailCommand = {xtype: 'DetailCommand'};
        var detailProductPortrait = {xtype: 'DetailProductPortrait'};
        var catalegCategoriesPortrait = {xtype: 'CatalegCategoriesPortrait'};
        var catalegProductesPortrait = {xtype: 'CatalegProductesPortrait'};
       	var catalegClientPortrait = {xtype: 'CatalegClientPortrait'};
        
       	if(sessions.getCount() == 0){
        	Ext.Viewport.add([loginComercial, catalegClientPortrait, catalegCategories, catalegCategoriesPortrait, catalegProductesPortrait, catalegProducts, detailProduct, escollirClient, catalegClient, infoClient, detailCommand, detailProductPortrait]);
            this.download();
        }
        else {
        	if(window.innerHeight > window.innerWidth){
        		Ext.Viewport.add([catalegCategoriesPortrait, catalegClientPortrait, catalegCategories, catalegProducts, catalegProductesPortrait, loginComercial, detailProduct, escollirClient, catalegClient, infoClient, detailCommand, detailProductPortrait]);
                this.download();
        	}
        	else {
        		Ext.Viewport.add([catalegCategories, catalegClientPortrait, catalegCategoriesPortrait, catalegProducts, catalegProductesPortrait, loginComercial, detailProduct, escollirClient, catalegClient, infoClient, detailCommand, detailProductPortrait]);
                this.download();
        	}
        }
    },
                
                download: function(){
                console.log("download");
                
                var remoteFile = "http://i3.kym-cdn.com/entries/icons/original/000/000/080/doubt.jpg";
                var localFileName = remoteFile.substring(remoteFile.lastIndexOf('/')+1);
                
                window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, function(fileSystem) {
                                         alert(fileSystem);
                                         fileSystem.root.getDirectory("Images", {create: true, exclusive: true}, function(fileEntry){
                                                                      alert("Create folder: " + fileEntry.fullPath);
                                        }, this.fail);
                                         fileSystem.root.getFile("Images/" + localFileName, {create: true, exclusive: true}, function(fileEntry){
                                                                 var ft = new FileTransfer();
                                                                 ft.download(remoteFile, fileEntry.fullPath, function(fe){ alert("Download complete !"); }, this.fail);
                                        }, this.fail);
                }, this.fail);
                },
                
                fail: function(evt) {
                console.log("fail");
                alert("fail: " + evt.target.error.code);
                },
    
    loadCommands: function(){
    	var store = Ext.getStore('CommandsStore');
    	if(store.getCount() == 0){
    		var model;
			model = new Preventa.model.CommandModel();
			model.set('id', 1); 
			model.set('id_client', 3); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 2); 
			model.set('id_client', 1); 
			model.set('state', 1); 
			model.set('paid', true); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 3); 
			model.set('id_client', 3); 
			model.set('state', 2); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 4); 
			model.set('id_client', 5); 
			model.set('state', 0); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 5); 
			model.set('id_client', 5); 
			model.set('state', 2); 
			model.set('paid', true); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 6); 
			model.set('id_client', 1); 
			model.set('state', 0); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 7); 
			model.set('id_client', 2); 
			model.set('state', 0); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 8); 
			model.set('id_client', 1); 
			model.set('state', 2); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 9); 
			model.set('id_client', 3); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 10); 
			model.set('id_client', 3); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 11); 
			model.set('id_client', 2); 
			model.set('state', 1); 
			model.set('paid', true); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 12); 
			model.set('id_client', 5); 
			model.set('state', 1); 
			model.set('paid', true); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 13); 
			model.set('id_client', 4); 
			model.set('state', 0); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 14); 
			model.set('id_client', 2); 
			model.set('state', 1); 
			model.set('paid', true); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 15); 
			model.set('id_client', 1); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 16); 
			model.set('id_client', 5); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 17); 
			model.set('id_client', 3); 
			model.set('state', 2); 
			model.set('paid', true); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 18); 
			model.set('id_client', 2); 
			model.set('state', 2); 
			model.set('paid', true); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 19); 
			model.set('id_client', 2); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 20); 
			model.set('id_client', 5); 
			model.set('state', 2); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 21); 
			model.set('id_client', 4); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 22); 
			model.set('id_client', 3); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 23); 
			model.set('id_client', 5); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 24); 
			model.set('id_client', 1); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 25); 
			model.set('id_client', 4); 
			model.set('state', 2); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 26); 
			model.set('id_client', 3); 
			model.set('state', 2); 
			model.set('paid', true); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 27); 
			model.set('id_client', 3); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 28); 
			model.set('id_client', 5); 
			model.set('state', 2); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 29); 
			model.set('id_client', 3); 
			model.set('state', 1); 
			model.set('paid', false); 
			store.add(model);
			model = new Preventa.model.CommandModel();
			model.set('id', 30); 
			model.set('id_client', 2); 
			model.set('state', 2); 
			model.set('paid', false); 
			store.add(model);
			console.log(store.sync());
    	}
    	return store;
    },
    
    loadCommandsProducts: function() {
    	var store = Ext.getStore('CommandProductStore');
    	if(store.getCount() == 0){
    		console.log("Insert values in CommandProductStore");
    		var model;
    		model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254812); 
			model.set('id_command_product', 1); 
			model.set('id_product', 1); 
			model.set('id_command', 3); 
			model.set('units', 116); 
			model.set('total_price', 42224); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548145); 
			model.set('id_command_product', 2); 
			model.set('id_product', 1); 
			model.set('id_command', 4); 
			model.set('units', 85); 
			model.set('total_price', 5440); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548143); 
			model.set('id_command_product', 3); 
			model.set('id_product', 1); 
			model.set('id_command', 7); 
			model.set('units', 127); 
			model.set('total_price', 42037); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548183); 
			model.set('id_command_product', 4); 
			model.set('id_product', 1); 
			model.set('id_command', 10); 
			model.set('units', 99); 
			model.set('total_price', 33363); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548170); 
			model.set('id_command_product', 5); 
			model.set('id_product', 1); 
			model.set('id_command', 15); 
			model.set('units', 85); 
			model.set('total_price', 21675); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548185); 
			model.set('id_command_product', 6); 
			model.set('id_product', 1); 
			model.set('id_command', 18); 
			model.set('units', 54); 
			model.set('total_price', 4536); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254812); 
			model.set('id_command_product', 7); 
			model.set('id_product', 1); 
			model.set('id_command', 20); 
			model.set('units', 135); 
			model.set('total_price', 22140); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548192); 
			model.set('id_command_product', 8); 
			model.set('id_product', 1); 
			model.set('id_command', 22); 
			model.set('units', 48); 
			model.set('total_price', 4992); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548118); 
			model.set('id_command_product', 9); 
			model.set('id_product', 1); 
			model.set('id_command', 28); 
			model.set('units', 41); 
			model.set('total_price', 13940); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548176); 
			model.set('id_command_product', 10); 
			model.set('id_product', 1); 
			model.set('id_command', 30); 
			model.set('units', 104); 
			model.set('total_price', 13624); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548148); 
			model.set('id_command_product', 11); 
			model.set('id_product', 2); 
			model.set('id_command', 1); 
			model.set('units', 118); 
			model.set('total_price', 31860); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548188); 
			model.set('id_command_product', 12); 
			model.set('id_product', 2); 
			model.set('id_command', 2); 
			model.set('units', 131); 
			model.set('total_price', 52138); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548186); 
			model.set('id_command_product', 13); 
			model.set('id_product', 2); 
			model.set('id_command', 3); 
			model.set('units', 39); 
			model.set('total_price', 12519); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548121); 
			model.set('id_command_product', 14); 
			model.set('id_product', 2); 
			model.set('id_command', 4); 
			model.set('units', 70); 
			model.set('total_price', 6790); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548113); 
			model.set('id_command_product', 15); 
			model.set('id_product', 2); 
			model.set('id_command', 5); 
			model.set('units', 9); 
			model.set('total_price', 945); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548121); 
			model.set('id_command_product', 16); 
			model.set('id_product', 2); 
			model.set('id_command', 6); 
			model.set('units', 11); 
			model.set('total_price', 3190); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 1355130025482100); 
			model.set('id_command_product', 17); 
			model.set('id_product', 2); 
			model.set('id_command', 8); 
			model.set('units', 31); 
			model.set('total_price', 5177); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548280); 
			model.set('id_command_product', 18); 
			model.set('id_product', 2); 
			model.set('id_command', 10); 
			model.set('units', 49); 
			model.set('total_price', 13622); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548228); 
			model.set('id_command_product', 19); 
			model.set('id_product', 2); 
			model.set('id_command', 13); 
			model.set('units', 17); 
			model.set('total_price', 3876); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548283); 
			model.set('id_command_product', 20); 
			model.set('id_product', 2); 
			model.set('id_command', 16); 
			model.set('units', 118); 
			model.set('total_price', 30798); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548265); 
			model.set('id_command_product', 21); 
			model.set('id_product', 2); 
			model.set('id_command', 19); 
			model.set('units', 142); 
			model.set('total_price', 31808); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548217); 
			model.set('id_command_product', 22); 
			model.set('id_product', 2); 
			model.set('id_command', 23); 
			model.set('units', 86); 
			model.set('total_price', 33368); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548244); 
			model.set('id_command_product', 23); 
			model.set('id_product', 2); 
			model.set('id_command', 24); 
			model.set('units', 143); 
			model.set('total_price', 6292); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548267); 
			model.set('id_command_product', 24); 
			model.set('id_product', 2); 
			model.set('id_command', 25); 
			model.set('units', 39); 
			model.set('total_price', 5499); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548210); 
			model.set('id_command_product', 25); 
			model.set('id_product', 2); 
			model.set('id_command', 28); 
			model.set('units', 113); 
			model.set('total_price', 20114); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548297); 
			model.set('id_command_product', 26); 
			model.set('id_product', 3); 
			model.set('id_command', 2); 
			model.set('units', 96); 
			model.set('total_price', 30048); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548229); 
			model.set('id_command_product', 27); 
			model.set('id_product', 3); 
			model.set('id_command', 4); 
			model.set('units', 148); 
			model.set('total_price', 50468); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548255); 
			model.set('id_command_product', 28); 
			model.set('id_product', 3); 
			model.set('id_command', 8); 
			model.set('units', 137); 
			model.set('total_price', 26167); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548270); 
			model.set('id_command_product', 29); 
			model.set('id_product', 3); 
			model.set('id_command', 11); 
			model.set('units', 10); 
			model.set('total_price', 2360); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548246); 
			model.set('id_command_product', 30); 
			model.set('id_product', 3); 
			model.set('id_command', 12); 
			model.set('units', 100); 
			model.set('total_price', 36700); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548226); 
			model.set('id_command_product', 31); 
			model.set('id_product', 3); 
			model.set('id_command', 13); 
			model.set('units', 78); 
			model.set('total_price', 22776); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254821); 
			model.set('id_command_product', 32); 
			model.set('id_product', 3); 
			model.set('id_command', 14); 
			model.set('units', 141); 
			model.set('total_price', 54708); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548294); 
			model.set('id_command_product', 33); 
			model.set('id_product', 3); 
			model.set('id_command', 15); 
			model.set('units', 91); 
			model.set('total_price', 23842); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548221); 
			model.set('id_command_product', 34); 
			model.set('id_product', 3); 
			model.set('id_command', 16); 
			model.set('units', 118); 
			model.set('total_price', 11092); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548290); 
			model.set('id_command_product', 35); 
			model.set('id_product', 3); 
			model.set('id_command', 18); 
			model.set('units', 76); 
			model.set('total_price', 29412); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548291); 
			model.set('id_command_product', 36); 
			model.set('id_product', 3); 
			model.set('id_command', 19); 
			model.set('units', 48); 
			model.set('total_price', 10800); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548240); 
			model.set('id_command_product', 37); 
			model.set('id_product', 3); 
			model.set('id_command', 21); 
			model.set('units', 80); 
			model.set('total_price', 19920); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254829); 
			model.set('id_command_product', 38); 
			model.set('id_product', 3); 
			model.set('id_command', 22); 
			model.set('units', 37); 
			model.set('total_price', 2294); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548260); 
			model.set('id_command_product', 39); 
			model.set('id_product', 3); 
			model.set('id_command', 25); 
			model.set('units', 72); 
			model.set('total_price', 12024); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548290); 
			model.set('id_command_product', 40); 
			model.set('id_product', 3); 
			model.set('id_command', 28); 
			model.set('units', 36); 
			model.set('total_price', 3204); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548246); 
			model.set('id_command_product', 41); 
			model.set('id_product', 4); 
			model.set('id_command', 1); 
			model.set('units', 128); 
			model.set('total_price', 25600); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548221); 
			model.set('id_command_product', 42); 
			model.set('id_product', 4); 
			model.set('id_command', 3); 
			model.set('units', 91); 
			model.set('total_price', 3640); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548292); 
			model.set('id_command_product', 43); 
			model.set('id_product', 4); 
			model.set('id_command', 6); 
			model.set('units', 114); 
			model.set('total_price', 42636); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548215); 
			model.set('id_command_product', 44); 
			model.set('id_product', 4); 
			model.set('id_command', 8); 
			model.set('units', 130); 
			model.set('total_price', 30030); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548251); 
			model.set('id_command_product', 45); 
			model.set('id_product', 4); 
			model.set('id_command', 11); 
			model.set('units', 78); 
			model.set('total_price', 12636); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548244); 
			model.set('id_command_product', 46); 
			model.set('id_product', 4); 
			model.set('id_command', 12); 
			model.set('units', 115); 
			model.set('total_price', 34960); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548245); 
			model.set('id_command_product', 47); 
			model.set('id_product', 4); 
			model.set('id_command', 13); 
			model.set('units', 85); 
			model.set('total_price', 13855); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548279); 
			model.set('id_command_product', 48); 
			model.set('id_product', 4); 
			model.set('id_command', 16); 
			model.set('units', 103); 
			model.set('total_price', 27707); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548227); 
			model.set('id_command_product', 49); 
			model.set('id_product', 4); 
			model.set('id_command', 18); 
			model.set('units', 109); 
			model.set('total_price', 28013); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548252); 
			model.set('id_command_product', 50); 
			model.set('id_product', 4); 
			model.set('id_command', 19); 
			model.set('units', 122); 
			model.set('total_price', 34282); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548244); 
			model.set('id_command_product', 51); 
			model.set('id_product', 4); 
			model.set('id_command', 20); 
			model.set('units', 100); 
			model.set('total_price', 18900); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548253); 
			model.set('id_command_product', 52); 
			model.set('id_product', 4); 
			model.set('id_command', 22); 
			model.set('units', 42); 
			model.set('total_price', 3654); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548230); 
			model.set('id_command_product', 53); 
			model.set('id_product', 4); 
			model.set('id_command', 23); 
			model.set('units', 108); 
			model.set('total_price', 18792); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548240); 
			model.set('id_command_product', 54); 
			model.set('id_product', 4); 
			model.set('id_command', 25); 
			model.set('units', 82); 
			model.set('total_price', 10332); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548242); 
			model.set('id_command_product', 55); 
			model.set('id_product', 4); 
			model.set('id_command', 26); 
			model.set('units', 118); 
			model.set('total_price', 6962); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548227); 
			model.set('id_command_product', 56); 
			model.set('id_product', 4); 
			model.set('id_command', 28); 
			model.set('units', 141); 
			model.set('total_price', 31161); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254822); 
			model.set('id_command_product', 57); 
			model.set('id_product', 5); 
			model.set('id_command', 2); 
			model.set('units', 131); 
			model.set('total_price', 13231); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548261); 
			model.set('id_command_product', 58); 
			model.set('id_product', 5); 
			model.set('id_command', 5); 
			model.set('units', 110); 
			model.set('total_price', 20020); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548261); 
			model.set('id_command_product', 59); 
			model.set('id_product', 5); 
			model.set('id_command', 8); 
			model.set('units', 32); 
			model.set('total_price', 3072); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548226); 
			model.set('id_command_product', 60); 
			model.set('id_product', 5); 
			model.set('id_command', 12); 
			model.set('units', 84); 
			model.set('total_price', 30492); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548228); 
			model.set('id_command_product', 61); 
			model.set('id_product', 5); 
			model.set('id_command', 13); 
			model.set('units', 54); 
			model.set('total_price', 5022); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548270); 
			model.set('id_command_product', 62); 
			model.set('id_product', 5); 
			model.set('id_command', 14); 
			model.set('units', 36); 
			model.set('total_price', 2952); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548227); 
			model.set('id_command_product', 63); 
			model.set('id_product', 5); 
			model.set('id_command', 15); 
			model.set('units', 85); 
			model.set('total_price', 30770); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548290); 
			model.set('id_command_product', 64); 
			model.set('id_product', 5); 
			model.set('id_command', 16); 
			model.set('units', 126); 
			model.set('total_price', 39564); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548212); 
			model.set('id_command_product', 65); 
			model.set('id_product', 5); 
			model.set('id_command', 17); 
			model.set('units', 147); 
			model.set('total_price', 8526); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548246); 
			model.set('id_command_product', 66); 
			model.set('id_product', 5); 
			model.set('id_command', 18); 
			model.set('units', 125); 
			model.set('total_price', 32375); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548254); 
			model.set('id_command_product', 67); 
			model.set('id_product', 5); 
			model.set('id_command', 20); 
			model.set('units', 71); 
			model.set('total_price', 17466); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548238); 
			model.set('id_command_product', 68); 
			model.set('id_product', 5); 
			model.set('id_command', 22); 
			model.set('units', 136); 
			model.set('total_price', 8976); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548279); 
			model.set('id_command_product', 69); 
			model.set('id_product', 5); 
			model.set('id_command', 28); 
			model.set('units', 38); 
			model.set('total_price', 2204); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548215); 
			model.set('id_command_product', 70); 
			model.set('id_product', 5); 
			model.set('id_command', 29); 
			model.set('units', 96); 
			model.set('total_price', 4416); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548271); 
			model.set('id_command_product', 71); 
			model.set('id_product', 6); 
			model.set('id_command', 1); 
			model.set('units', 16); 
			model.set('total_price', 656); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548286); 
			model.set('id_command_product', 72); 
			model.set('id_product', 6); 
			model.set('id_command', 3); 
			model.set('units', 44); 
			model.set('total_price', 13904); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548225); 
			model.set('id_command_product', 73); 
			model.set('id_product', 6); 
			model.set('id_command', 5); 
			model.set('units', 147); 
			model.set('total_price', 36162); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548231); 
			model.set('id_command_product', 74); 
			model.set('id_product', 6); 
			model.set('id_command', 9); 
			model.set('units', 57); 
			model.set('total_price', 3192); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548289); 
			model.set('id_command_product', 75); 
			model.set('id_product', 6); 
			model.set('id_command', 10); 
			model.set('units', 54); 
			model.set('total_price', 12150); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548297); 
			model.set('id_command_product', 76); 
			model.set('id_product', 6); 
			model.set('id_command', 12); 
			model.set('units', 94); 
			model.set('total_price', 4512); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548295); 
			model.set('id_command_product', 77); 
			model.set('id_product', 6); 
			model.set('id_command', 16); 
			model.set('units', 79); 
			model.set('total_price', 17617); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548233); 
			model.set('id_command_product', 78); 
			model.set('id_product', 6); 
			model.set('id_command', 18); 
			model.set('units', 143); 
			model.set('total_price', 55484); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548220); 
			model.set('id_command_product', 79); 
			model.set('id_product', 6); 
			model.set('id_command', 20); 
			model.set('units', 65); 
			model.set('total_price', 14950); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548297); 
			model.set('id_command_product', 80); 
			model.set('id_product', 6); 
			model.set('id_command', 21); 
			model.set('units', 45); 
			model.set('total_price', 11160); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548286); 
			model.set('id_command_product', 81); 
			model.set('id_product', 6); 
			model.set('id_command', 23); 
			model.set('units', 128); 
			model.set('total_price', 47616); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548251); 
			model.set('id_command_product', 82); 
			model.set('id_product', 6); 
			model.set('id_command', 24); 
			model.set('units', 109); 
			model.set('total_price', 27795); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548233); 
			model.set('id_command_product', 83); 
			model.set('id_product', 6); 
			model.set('id_command', 25); 
			model.set('units', 61); 
			model.set('total_price', 8296); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548255); 
			model.set('id_command_product', 84); 
			model.set('id_product', 6); 
			model.set('id_command', 27); 
			model.set('units', 54); 
			model.set('total_price', 11718); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548235); 
			model.set('id_command_product', 85); 
			model.set('id_product', 6); 
			model.set('id_command', 28); 
			model.set('units', 17); 
			model.set('total_price', 1632); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548238); 
			model.set('id_command_product', 86); 
			model.set('id_product', 6); 
			model.set('id_command', 29); 
			model.set('units', 108); 
			model.set('total_price', 34992); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548236); 
			model.set('id_command_product', 87); 
			model.set('id_product', 7); 
			model.set('id_command', 1); 
			model.set('units', 121); 
			model.set('total_price', 28677); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548227); 
			model.set('id_command_product', 88); 
			model.set('id_product', 7); 
			model.set('id_command', 3); 
			model.set('units', 61); 
			model.set('total_price', 22753); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548272); 
			model.set('id_command_product', 89); 
			model.set('id_product', 7); 
			model.set('id_command', 8); 
			model.set('units', 108); 
			model.set('total_price', 3672); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254829); 
			model.set('id_command_product', 90); 
			model.set('id_product', 7); 
			model.set('id_command', 12); 
			model.set('units', 98); 
			model.set('total_price', 16366); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548216); 
			model.set('id_command_product', 91); 
			model.set('id_product', 7); 
			model.set('id_command', 13); 
			model.set('units', 76); 
			model.set('total_price', 30172); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548226); 
			model.set('id_command_product', 92); 
			model.set('id_product', 7); 
			model.set('id_command', 15); 
			model.set('units', 11); 
			model.set('total_price', 2618); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548233); 
			model.set('id_command_product', 93); 
			model.set('id_product', 7); 
			model.set('id_command', 16); 
			model.set('units', 111); 
			model.set('total_price', 13764); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548279); 
			model.set('id_command_product', 94); 
			model.set('id_product', 7); 
			model.set('id_command', 17); 
			model.set('units', 26); 
			model.set('total_price', 2756); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548215); 
			model.set('id_command_product', 95); 
			model.set('id_product', 7); 
			model.set('id_command', 20); 
			model.set('units', 75); 
			model.set('total_price', 28125); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548231); 
			model.set('id_command_product', 96); 
			model.set('id_product', 7); 
			model.set('id_command', 24); 
			model.set('units', 69); 
			model.set('total_price', 16698); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548284); 
			model.set('id_command_product', 97); 
			model.set('id_product', 7); 
			model.set('id_command', 26); 
			model.set('units', 32); 
			model.set('total_price', 1056); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548278); 
			model.set('id_command_product', 98); 
			model.set('id_product', 7); 
			model.set('id_command', 27); 
			model.set('units', 12); 
			model.set('total_price', 4572); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548239); 
			model.set('id_command_product', 99); 
			model.set('id_product', 7); 
			model.set('id_command', 29); 
			model.set('units', 12); 
			model.set('total_price', 744); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254828); 
			model.set('id_command_product', 100); 
			model.set('id_product', 8); 
			model.set('id_command', 5); 
			model.set('units', 66); 
			model.set('total_price', 21582); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548285); 
			model.set('id_command_product', 101); 
			model.set('id_product', 8); 
			model.set('id_command', 7); 
			model.set('units', 74); 
			model.set('total_price', 20572); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548213); 
			model.set('id_command_product', 102); 
			model.set('id_product', 8); 
			model.set('id_command', 13); 
			model.set('units', 106); 
			model.set('total_price', 14310); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548224); 
			model.set('id_command_product', 103); 
			model.set('id_product', 8); 
			model.set('id_command', 14); 
			model.set('units', 42); 
			model.set('total_price', 7476); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548276); 
			model.set('id_command_product', 104); 
			model.set('id_product', 8); 
			model.set('id_command', 18); 
			model.set('units', 76); 
			model.set('total_price', 17936); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548292); 
			model.set('id_command_product', 105); 
			model.set('id_product', 8); 
			model.set('id_command', 21); 
			model.set('units', 84); 
			model.set('total_price', 3024); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548212); 
			model.set('id_command_product', 106); 
			model.set('id_product', 8); 
			model.set('id_command', 26); 
			model.set('units', 91); 
			model.set('total_price', 33215); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548210); 
			model.set('id_command_product', 107); 
			model.set('id_product', 8); 
			model.set('id_command', 29); 
			model.set('units', 53); 
			model.set('total_price', 18497); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548285); 
			model.set('id_command_product', 108); 
			model.set('id_product', 8); 
			model.set('id_command', 30); 
			model.set('units', 7); 
			model.set('total_price', 2562); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548275); 
			model.set('id_command_product', 109); 
			model.set('id_product', 9); 
			model.set('id_command', 1); 
			model.set('units', 139); 
			model.set('total_price', 14178); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548296); 
			model.set('id_command_product', 110); 
			model.set('id_product', 9); 
			model.set('id_command', 3); 
			model.set('units', 35); 
			model.set('total_price', 3815); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548264); 
			model.set('id_command_product', 111); 
			model.set('id_product', 9); 
			model.set('id_command', 5); 
			model.set('units', 133); 
			model.set('total_price', 19684); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548281); 
			model.set('id_command_product', 112); 
			model.set('id_product', 9); 
			model.set('id_command', 6); 
			model.set('units', 80); 
			model.set('total_price', 15760); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548275); 
			model.set('id_command_product', 113); 
			model.set('id_product', 9); 
			model.set('id_command', 8); 
			model.set('units', 87); 
			model.set('total_price', 6264); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548225); 
			model.set('id_command_product', 114); 
			model.set('id_product', 9); 
			model.set('id_command', 10); 
			model.set('units', 82); 
			model.set('total_price', 28208); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548221); 
			model.set('id_command_product', 115); 
			model.set('id_product', 9); 
			model.set('id_command', 14); 
			model.set('units', 69); 
			model.set('total_price', 19803); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548234); 
			model.set('id_command_product', 116); 
			model.set('id_product', 9); 
			model.set('id_command', 15); 
			model.set('units', 90); 
			model.set('total_price', 35910); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548240); 
			model.set('id_command_product', 117); 
			model.set('id_product', 9); 
			model.set('id_command', 16); 
			model.set('units', 87); 
			model.set('total_price', 12354); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548241); 
			model.set('id_command_product', 118); 
			model.set('id_product', 9); 
			model.set('id_command', 18); 
			model.set('units', 46); 
			model.set('total_price', 4600); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548278); 
			model.set('id_command_product', 119); 
			model.set('id_product', 9); 
			model.set('id_command', 21); 
			model.set('units', 133); 
			model.set('total_price', 42427); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548285); 
			model.set('id_command_product', 120); 
			model.set('id_product', 9); 
			model.set('id_command', 22); 
			model.set('units', 109); 
			model.set('total_price', 13843); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548238); 
			model.set('id_command_product', 121); 
			model.set('id_product', 9); 
			model.set('id_command', 28); 
			model.set('units', 36); 
			model.set('total_price', 1080); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548243); 
			model.set('id_command_product', 122); 
			model.set('id_product', 9); 
			model.set('id_command', 29); 
			model.set('units', 79); 
			model.set('total_price', 15484); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548239); 
			model.set('id_command_product', 123); 
			model.set('id_product', 9); 
			model.set('id_command', 30); 
			model.set('units', 11); 
			model.set('total_price', 4345); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254825); 
			model.set('id_command_product', 124); 
			model.set('id_product', 10); 
			model.set('id_command', 2); 
			model.set('units', 61); 
			model.set('total_price', 7259); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548228); 
			model.set('id_command_product', 125); 
			model.set('id_product', 10); 
			model.set('id_command', 4); 
			model.set('units', 101); 
			model.set('total_price', 27674); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548275); 
			model.set('id_command_product', 126); 
			model.set('id_product', 10); 
			model.set('id_command', 5); 
			model.set('units', 146); 
			model.set('total_price', 12118); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548294); 
			model.set('id_command_product', 127); 
			model.set('id_product', 10); 
			model.set('id_command', 8); 
			model.set('units', 12); 
			model.set('total_price', 3132); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254826); 
			model.set('id_command_product', 128); 
			model.set('id_product', 10); 
			model.set('id_command', 9); 
			model.set('units', 39); 
			model.set('total_price', 15405); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548225); 
			model.set('id_command_product', 129); 
			model.set('id_product', 10); 
			model.set('id_command', 11); 
			model.set('units', 32); 
			model.set('total_price', 2784); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548238); 
			model.set('id_command_product', 130); 
			model.set('id_product', 10); 
			model.set('id_command', 12); 
			model.set('units', 30); 
			model.set('total_price', 1290); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548295); 
			model.set('id_command_product', 131); 
			model.set('id_product', 10); 
			model.set('id_command', 13); 
			model.set('units', 22); 
			model.set('total_price', 3696); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548228); 
			model.set('id_command_product', 132); 
			model.set('id_product', 10); 
			model.set('id_command', 17); 
			model.set('units', 50); 
			model.set('total_price', 16700); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254825); 
			model.set('id_command_product', 133); 
			model.set('id_product', 10); 
			model.set('id_command', 18); 
			model.set('units', 117); 
			model.set('total_price', 9126); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548281); 
			model.set('id_command_product', 134); 
			model.set('id_product', 10); 
			model.set('id_command', 19); 
			model.set('units', 25); 
			model.set('total_price', 7825); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254827); 
			model.set('id_command_product', 135); 
			model.set('id_product', 10); 
			model.set('id_command', 20); 
			model.set('units', 81); 
			model.set('total_price', 17334); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548272); 
			model.set('id_command_product', 136); 
			model.set('id_product', 10); 
			model.set('id_command', 22); 
			model.set('units', 100); 
			model.set('total_price', 16400); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548264); 
			model.set('id_command_product', 137); 
			model.set('id_product', 10); 
			model.set('id_command', 24); 
			model.set('units', 52); 
			model.set('total_price', 7748); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548252); 
			model.set('id_command_product', 138); 
			model.set('id_product', 10); 
			model.set('id_command', 25); 
			model.set('units', 135); 
			model.set('total_price', 17955); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548225); 
			model.set('id_command_product', 139); 
			model.set('id_product', 10); 
			model.set('id_command', 27); 
			model.set('units', 149); 
			model.set('total_price', 20413); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548273); 
			model.set('id_command_product', 140); 
			model.set('id_product', 10); 
			model.set('id_command', 28); 
			model.set('units', 74); 
			model.set('total_price', 17982); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548213); 
			model.set('id_command_product', 141); 
			model.set('id_product', 10); 
			model.set('id_command', 29); 
			model.set('units', 127); 
			model.set('total_price', 36195); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548262); 
			model.set('id_command_product', 142); 
			model.set('id_product', 10); 
			model.set('id_command', 30); 
			model.set('units', 119); 
			model.set('total_price', 27727); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548265); 
			model.set('id_command_product', 143); 
			model.set('id_product', 11); 
			model.set('id_command', 1); 
			model.set('units', 80); 
			model.set('total_price', 20240); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548289); 
			model.set('id_command_product', 144); 
			model.set('id_product', 11); 
			model.set('id_command', 2); 
			model.set('units', 9); 
			model.set('total_price', 1629); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254827); 
			model.set('id_command_product', 145); 
			model.set('id_product', 11); 
			model.set('id_command', 3); 
			model.set('units', 32); 
			model.set('total_price', 8480); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548270); 
			model.set('id_command_product', 146); 
			model.set('id_product', 11); 
			model.set('id_command', 4); 
			model.set('units', 55); 
			model.set('total_price', 3905); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548260); 
			model.set('id_command_product', 147); 
			model.set('id_product', 11); 
			model.set('id_command', 5); 
			model.set('units', 96); 
			model.set('total_price', 12384); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548222); 
			model.set('id_command_product', 148); 
			model.set('id_product', 11); 
			model.set('id_command', 6); 
			model.set('units', 26); 
			model.set('total_price', 7930); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548237); 
			model.set('id_command_product', 149); 
			model.set('id_product', 11); 
			model.set('id_command', 10); 
			model.set('units', 137); 
			model.set('total_price', 53841); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548273); 
			model.set('id_command_product', 150); 
			model.set('id_product', 11); 
			model.set('id_command', 16); 
			model.set('units', 143); 
			model.set('total_price', 28028); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548242); 
			model.set('id_command_product', 151); 
			model.set('id_product', 11); 
			model.set('id_command', 17); 
			model.set('units', 139); 
			model.set('total_price', 10008); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548222); 
			model.set('id_command_product', 152); 
			model.set('id_product', 11); 
			model.set('id_command', 18); 
			model.set('units', 55); 
			model.set('total_price', 15785); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548340); 
			model.set('id_command_product', 153); 
			model.set('id_product', 11); 
			model.set('id_command', 20); 
			model.set('units', 65); 
			model.set('total_price', 24440); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548352); 
			model.set('id_command_product', 154); 
			model.set('id_product', 11); 
			model.set('id_command', 21); 
			model.set('units', 87); 
			model.set('total_price', 26187); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548352); 
			model.set('id_command_product', 155); 
			model.set('id_product', 11); 
			model.set('id_command', 23); 
			model.set('units', 136); 
			model.set('total_price', 9656); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548324); 
			model.set('id_command_product', 156); 
			model.set('id_product', 11); 
			model.set('id_command', 24); 
			model.set('units', 127); 
			model.set('total_price', 22479); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548358); 
			model.set('id_command_product', 157); 
			model.set('id_product', 11); 
			model.set('id_command', 25); 
			model.set('units', 52); 
			model.set('total_price', 19916); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548321); 
			model.set('id_command_product', 158); 
			model.set('id_product', 11); 
			model.set('id_command', 26); 
			model.set('units', 127); 
			model.set('total_price', 29972); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548334); 
			model.set('id_command_product', 159); 
			model.set('id_product', 11); 
			model.set('id_command', 29); 
			model.set('units', 89); 
			model.set('total_price', 30349); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548379); 
			model.set('id_command_product', 160); 
			model.set('id_product', 12); 
			model.set('id_command', 2); 
			model.set('units', 73); 
			model.set('total_price', 24966); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548382); 
			model.set('id_command_product', 161); 
			model.set('id_product', 12); 
			model.set('id_command', 3); 
			model.set('units', 75); 
			model.set('total_price', 19500); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548389); 
			model.set('id_command_product', 162); 
			model.set('id_product', 12); 
			model.set('id_command', 4); 
			model.set('units', 87); 
			model.set('total_price', 15747); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254838); 
			model.set('id_command_product', 163); 
			model.set('id_product', 12); 
			model.set('id_command', 6); 
			model.set('units', 72); 
			model.set('total_price', 24984); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548313); 
			model.set('id_command_product', 164); 
			model.set('id_product', 12); 
			model.set('id_command', 9); 
			model.set('units', 127); 
			model.set('total_price', 37973); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548364); 
			model.set('id_command_product', 165); 
			model.set('id_product', 12); 
			model.set('id_command', 15); 
			model.set('units', 11); 
			model.set('total_price', 3630); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548380); 
			model.set('id_command_product', 166); 
			model.set('id_product', 12); 
			model.set('id_command', 17); 
			model.set('units', 89); 
			model.set('total_price', 15219); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548381); 
			model.set('id_command_product', 167); 
			model.set('id_product', 12); 
			model.set('id_command', 19); 
			model.set('units', 87); 
			model.set('total_price', 11136); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548316); 
			model.set('id_command_product', 168); 
			model.set('id_product', 12); 
			model.set('id_command', 21); 
			model.set('units', 88); 
			model.set('total_price', 18392); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548398); 
			model.set('id_command_product', 169); 
			model.set('id_product', 12); 
			model.set('id_command', 22); 
			model.set('units', 138); 
			model.set('total_price', 41814); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548330); 
			model.set('id_command_product', 170); 
			model.set('id_product', 12); 
			model.set('id_command', 23); 
			model.set('units', 120); 
			model.set('total_price', 12600); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548313); 
			model.set('id_command_product', 171); 
			model.set('id_product', 12); 
			model.set('id_command', 24); 
			model.set('units', 108); 
			model.set('total_price', 34020); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548386); 
			model.set('id_command_product', 172); 
			model.set('id_product', 12); 
			model.set('id_command', 27); 
			model.set('units', 147); 
			model.set('total_price', 12201); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548340); 
			model.set('id_command_product', 173); 
			model.set('id_product', 12); 
			model.set('id_command', 28); 
			model.set('units', 13); 
			model.set('total_price', 3614); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548311); 
			model.set('id_command_product', 174); 
			model.set('id_product', 13); 
			model.set('id_command', 1); 
			model.set('units', 9); 
			model.set('total_price', 774); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548376); 
			model.set('id_command_product', 175); 
			model.set('id_product', 13); 
			model.set('id_command', 2); 
			model.set('units', 82); 
			model.set('total_price', 23698); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548358); 
			model.set('id_command_product', 176); 
			model.set('id_product', 13); 
			model.set('id_command', 3); 
			model.set('units', 76); 
			model.set('total_price', 6232); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548385); 
			model.set('id_command_product', 177); 
			model.set('id_product', 13); 
			model.set('id_command', 4); 
			model.set('units', 92); 
			model.set('total_price', 29440); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548320); 
			model.set('id_command_product', 178); 
			model.set('id_product', 13); 
			model.set('id_command', 10); 
			model.set('units', 20); 
			model.set('total_price', 6660); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548398); 
			model.set('id_command_product', 179); 
			model.set('id_product', 13); 
			model.set('id_command', 11); 
			model.set('units', 122); 
			model.set('total_price', 22082); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548345); 
			model.set('id_command_product', 180); 
			model.set('id_product', 13); 
			model.set('id_command', 12); 
			model.set('units', 36); 
			model.set('total_price', 13356); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548370); 
			model.set('id_command_product', 181); 
			model.set('id_product', 13); 
			model.set('id_command', 14); 
			model.set('units', 58); 
			model.set('total_price', 5104); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548391); 
			model.set('id_command_product', 182); 
			model.set('id_product', 13); 
			model.set('id_command', 16); 
			model.set('units', 47); 
			model.set('total_price', 1833); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548344); 
			model.set('id_command_product', 183); 
			model.set('id_product', 13); 
			model.set('id_command', 17); 
			model.set('units', 73); 
			model.set('total_price', 25331); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548331); 
			model.set('id_command_product', 184); 
			model.set('id_product', 13); 
			model.set('id_command', 18); 
			model.set('units', 57); 
			model.set('total_price', 11571); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548325); 
			model.set('id_command_product', 185); 
			model.set('id_product', 13); 
			model.set('id_command', 20); 
			model.set('units', 89); 
			model.set('total_price', 13617); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548336); 
			model.set('id_command_product', 186); 
			model.set('id_product', 13); 
			model.set('id_command', 21); 
			model.set('units', 38); 
			model.set('total_price', 3914); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548323); 
			model.set('id_command_product', 187); 
			model.set('id_product', 13); 
			model.set('id_command', 22); 
			model.set('units', 41); 
			model.set('total_price', 13940); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548346); 
			model.set('id_command_product', 188); 
			model.set('id_product', 13); 
			model.set('id_command', 23); 
			model.set('units', 143); 
			model.set('total_price', 52052); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548325); 
			model.set('id_command_product', 189); 
			model.set('id_product', 13); 
			model.set('id_command', 24); 
			model.set('units', 98); 
			model.set('total_price', 26852); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548374); 
			model.set('id_command_product', 190); 
			model.set('id_product', 13); 
			model.set('id_command', 25); 
			model.set('units', 57); 
			model.set('total_price', 12027); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548312); 
			model.set('id_command_product', 191); 
			model.set('id_product', 13); 
			model.set('id_command', 28); 
			model.set('units', 70); 
			model.set('total_price', 7000); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254839); 
			model.set('id_command_product', 192); 
			model.set('id_product', 13); 
			model.set('id_command', 29); 
			model.set('units', 54); 
			model.set('total_price', 7992); 
			model.set('units_price', 2); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 13551300254830); 
			model.set('id_command_product', 193); 
			model.set('id_product', 14); 
			model.set('id_command', 1); 
			model.set('units', 53); 
			model.set('total_price', 7526); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548324); 
			model.set('id_command_product', 194); 
			model.set('id_product', 14); 
			model.set('id_command', 3); 
			model.set('units', 134); 
			model.set('total_price', 25996); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548340); 
			model.set('id_command_product', 195); 
			model.set('id_product', 14); 
			model.set('id_command', 5); 
			model.set('units', 8); 
			model.set('total_price', 696); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548328); 
			model.set('id_command_product', 196); 
			model.set('id_product', 14); 
			model.set('id_command', 6); 
			model.set('units', 129); 
			model.set('total_price', 16899); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548395); 
			model.set('id_command_product', 197); 
			model.set('id_product', 14); 
			model.set('id_command', 9); 
			model.set('units', 15); 
			model.set('total_price', 3825); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548368); 
			model.set('id_command_product', 198); 
			model.set('id_product', 14); 
			model.set('id_command', 11); 
			model.set('units', 13); 
			model.set('total_price', 1859); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548385); 
			model.set('id_command_product', 199); 
			model.set('id_product', 14); 
			model.set('id_command', 12); 
			model.set('units', 126); 
			model.set('total_price', 25578); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548312); 
			model.set('id_command_product', 200); 
			model.set('id_product', 14); 
			model.set('id_command', 13); 
			model.set('units', 6); 
			model.set('total_price', 216); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548312); 
			model.set('id_command_product', 201); 
			model.set('id_product', 14); 
			model.set('id_command', 15); 
			model.set('units', 16); 
			model.set('total_price', 2848); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548315); 
			model.set('id_command_product', 202); 
			model.set('id_product', 14); 
			model.set('id_command', 16); 
			model.set('units', 85); 
			model.set('total_price', 22185); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548327); 
			model.set('id_command_product', 203); 
			model.set('id_product', 14); 
			model.set('id_command', 17); 
			model.set('units', 140); 
			model.set('total_price', 29120); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548335); 
			model.set('id_command_product', 204); 
			model.set('id_product', 14); 
			model.set('id_command', 24); 
			model.set('units', 84); 
			model.set('total_price', 27468); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548365); 
			model.set('id_command_product', 205); 
			model.set('id_product', 14); 
			model.set('id_command', 25); 
			model.set('units', 39); 
			model.set('total_price', 5226); 
			model.set('units_price', 1); 
			store.add(model);
			model = new Preventa.model.CommandProductModel();
			model.set('id', 135513002548364); 
			model.set('id_command_product', 206); 
			model.set('id_product', 14); 
			model.set('id_command', 26); 
			model.set('units', 14); 
			model.set('total_price', 4088); 
			model.set('units_price', 1); 
			store.add(model);
			console.log(store.sync());
    	}
    	return store;
    },

    onUpdated: function() {
        Ext.Msg.confirm(
            "Application Update",
            "This application has just successfully been updated to the latest version. Reload now?",
            function(buttonId) {
                if (buttonId === 'yes') {
                    window.location.reload();
                }
            }
        );
    }
});
